- name: Patch OS playbook
  hosts: all
  become: yes 
  
  tasks:
    - name: Patching Red Hat Enterprise Linux
      yum:
        name: '*'
        state: latest
        
    - debug:
        msg: "Patched Red Hat Enterprise Linux. Now at: {{ ansible_distribution_version }}"
